<?php
$routes = [
    '/' => ['view' => 'home/index'],
    '/catalog' => ['view' => 'product/catalog'],
    '/products' => ['view' => 'product/catalog'],
    '/product' => ['view' => 'product/detail'],
    '/cart' => ['view' => 'cart/index'],
    '/checkout' => ['view' => 'checkout/index'],
    '/login' => ['view' => 'auth/login'],
    '/register' => ['view' => 'auth/register'],
    '/logout' => ['action' => 'logout'],

    '/user/dashboard' => ['view' => 'user/dashboard'],
    '/user/addresses' => ['view' => 'user/addresses'],
    '/user/address-edit' => ['view' => 'user/address_edit'],
    '/user/orders' => ['view' => 'user/orders'],
    '/user/order-detail' => ['view' => 'user/order_detail'],
    '/user/invoice' => ['view' => 'user/invoice'],
    '/user/invoice-pdf' => ['view' => 'user/invoice_pdf'],

    '/admin/dashboard' => ['view' => 'admin/dashboard'],
    '/admin/products' => ['view' => 'admin/products/index'],
    '/admin/products/create' => ['view' => 'admin/products/create'],
    '/admin/products/edit' => ['view' => 'admin/products/edit'],
    '/admin/products/stock' => ['view' => 'admin/products/stock'],
    '/admin/products/gallery' => ['view' => 'admin/products/gallery'],
    '/admin/brands' => ['view' => 'admin/brands'],
    '/admin/categories' => ['view' => 'admin/categories'],
    '/admin/orders' => ['view' => 'admin/orders'],
    '/admin/order-detail' => ['view' => 'admin/order_detail'],
    '/admin/payments' => ['view' => 'admin/payments'],
    '/admin/shipping' => ['view' => 'admin/shipping'],
    '/admin/reports' => ['view' => 'admin/reports'],
    '/admin/reports-export' => ['view' => 'admin/reports_export'],
    '/admin/logs' => ['view' => 'admin/logs'],
];